repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --line-length=120
        name: black code formatter

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: debug-statements
      # - id: no-commit-to-branch
      #   args:
      #     - --branch=master

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-no-log-warn
        name: check for deprecated logging.warn()

  - repo: https://github.com/hadialqattan/pycln
    rev: v1.2.5
    hooks:
      - id: pycln
        name: remove unused imports

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - --line-length=120
          - --profile=black
        name: sort python imports

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
          - --per-file-ignores=tests/*:F811,F401,__init__.py:F401
        name: flake8 style convention

  - repo: https://github.com/pycqa/pylint
    rev: v2.13.7
    hooks:
      - id: pylint
        args:
          - --max-line-length=120
          - --disable=E0401
          - --fail-under=5
        verbose: true
        # entry: bash -c 'pylint "$@" || true' -- # don't fail on pylint errors

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
      - id: pyupgrade
        args:
          - --py36-plus
        name: automatically upgrade syntax
